/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as DuelRouteImport } from './routes/duel'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as PortefeuilleRouteImport } from './routes/portefeuille'
import { Route as RetraitRouteImport } from './routes/retrait'
import { Route as StatutsRouteImport } from './routes/statuts'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as PlayCategoryRouteImport } from './routes/play.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelRoute = DuelRouteImport.update({
  id: '/duel',
  path: '/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const PortefeuilleRoute = PortefeuilleRouteImport.update({
  id: '/portefeuille',
  path: '/portefeuille',
  getParentRoute: () => rootRouteImport,
} as any)
const RetraitRoute = RetraitRouteImport.update({
  id: '/retrait',
  path: '/retrait',
  getParentRoute: () => rootRouteImport,
} as any)
const StatutsRoute = StatutsRouteImport.update({
  id: '/statuts',
  path: '/statuts',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCategoryRoute = PlayCategoryRouteImport.update({
  id: '/play/$category',
  path: '/play/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conditions': typeof ConditionsRoute
  '/duel': typeof DuelRoute
  '/explorer': typeof ExplorerRoute
  '/faq': typeof FaqRoute
  '/invite': typeof InviteRoute
  '/portefeuille': typeof PortefeuilleRoute
  '/retrait': typeof RetraitRoute
  '/statuts': typeof StatutsRoute
  '/p/$slug': typeof PSlugRoute
  '/play/$category': typeof PlayCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conditions': typeof ConditionsRoute
  '/duel': typeof DuelRoute
  '/explorer': typeof ExplorerRoute
  '/faq': typeof FaqRoute
  '/invite': typeof InviteRoute
  '/portefeuille': typeof PortefeuilleRoute
  '/retrait': typeof RetraitRoute
  '/statuts': typeof StatutsRoute
  '/p/$slug': typeof PSlugRoute
  '/play/$category': typeof PlayCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conditions': typeof ConditionsRoute
  '/duel': typeof DuelRoute
  '/explorer': typeof ExplorerRoute
  '/faq': typeof FaqRoute
  '/invite': typeof InviteRoute
  '/portefeuille': typeof PortefeuilleRoute
  '/retrait': typeof RetraitRoute
  '/statuts': typeof StatutsRoute
  '/p/$slug': typeof PSlugRoute
  '/play/$category': typeof PlayCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/conditions'
    | '/duel'
    | '/explorer'
    | '/faq'
    | '/invite'
    | '/portefeuille'
    | '/retrait'
    | '/statuts'
    | '/p/$slug'
    | '/play/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/conditions'
    | '/duel'
    | '/explorer'
    | '/faq'
    | '/invite'
    | '/portefeuille'
    | '/retrait'
    | '/statuts'
    | '/p/$slug'
    | '/play/$category'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/conditions'
    | '/duel'
    | '/explorer'
    | '/faq'
    | '/invite'
    | '/portefeuille'
    | '/retrait'
    | '/statuts'
    | '/p/$slug'
    | '/play/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ConditionsRoute: typeof ConditionsRoute
  DuelRoute: typeof DuelRoute
  ExplorerRoute: typeof ExplorerRoute
  FaqRoute: typeof FaqRoute
  InviteRoute: typeof InviteRoute
  PortefeuilleRoute: typeof PortefeuilleRoute
  RetraitRoute: typeof RetraitRoute
  StatutsRoute: typeof StatutsRoute
  PSlugRoute: typeof PSlugRoute
  PlayCategoryRoute: typeof PlayCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel': {
      id: '/duel'
      path: '/duel'
      fullPath: '/duel'
      preLoaderRoute: typeof DuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portefeuille': {
      id: '/portefeuille'
      path: '/portefeuille'
      fullPath: '/portefeuille'
      preLoaderRoute: typeof PortefeuilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrait': {
      id: '/retrait'
      path: '/retrait'
      fullPath: '/retrait'
      preLoaderRoute: typeof RetraitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statuts': {
      id: '/statuts'
      path: '/statuts'
      fullPath: '/statuts'
      preLoaderRoute: typeof StatutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$category': {
      id: '/play/$category'
      path: '/play/$category'
      fullPath: '/play/$category'
      preLoaderRoute: typeof PlayCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ConditionsRoute: ConditionsRoute,
  DuelRoute: DuelRoute,
  ExplorerRoute: ExplorerRoute,
  FaqRoute: FaqRoute,
  InviteRoute: InviteRoute,
  PortefeuilleRoute: PortefeuilleRoute,
  RetraitRoute: RetraitRoute,
  StatutsRoute: StatutsRoute,
  PSlugRoute: PSlugRoute,
  PlayCategoryRoute: PlayCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
